services:
  djangoapi:
    restart: unless-stopped
    build:
      context: ./djangoapi
      args:
        - USER_ID=${DJANGOAPI_USER_ID}
        - GROUP_ID=${DJANGOAPI_GROUP_ID}
        - USERNAME=${DJANGOAPI_USERNAME}
    command: gunicorn djangoapi.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./djangoapi:/usr/src/app
    ports:
      - 127.0.0.1:8006:8000
    env_file:
      - .env.prod
    networks:
      - joamona-dj-api_postgis

networks:
  joamona-dj-api_postgis:
    external: true
